import styles from '../styles/Home.module.css';
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <div className="flex justify-center">
        <h1 className="p-5 text-3xl text-emerald-400">About Ready Set Bet</h1>
      </div>
      <div className="p-5 border-b-2">
        <h1 className="text-xl text-slate-200 p-5 border-b-2">What is Ready Set Bet?</h1>
        <p>Ready Set Bet is a decentalized platform that allows users to take secure bets with a great deal of flexibility regarding exactly what they are betting on. Built on UMA Protocol, betting contracts can be written to accomodate any sort of publicly verifiable information. For example, one could ask Ready Set Bet something such as, "Will the temperature of Bogota, Colombia exceed 20C on October 25, 2022?" UMA will then use it's unique settlement mechanism to provide a corrrect answer to that question. In this way, users can take bets on virtually any topic. "Is Bitcoin going to reach $1M USD by 2025?", "Will the Russian-Ukrainian conflict end within 2022?", "Will Sushiswap be hacked for a loss of over $10M USD within the next year?" These are all bets that can be taken on Ready Set Bet
        </p>
        <h1 className="text-xl text-slate-200 p-5 border-b-2">What was the inspiration behind Ready Set Bet?</h1>
        <p>I originally came up with the idea after the rather notorious bet that was taken on Crypto Twitter by AIGod and DoKwon regarding the price LUNA in March of 2022. At the time, LUNA was trading at well over $100 with a marketcap of around $40B USD. While many people stated that the mechanics of LUNA were unsustainable, the fanbase of the token was so strong that most people disregarded such concerns. After months of arguing online on Twitter, AIGod and DoKwon eventually decided to make a $1M that LUNA would be worth less than $88 by March of 2023. Upon the news, other actors such as Crypto Twitter personality Gigantic-Rebirth decided that they wanted in on the bet. GR upped the ante by betting DoKwon $20M USD on the exact same terms - LUNA would be worth less than $88 by March of 2023. Now the question became, how would they secure the bet? There are currently no platforms to secure such a bet, so the parties involved agreed to escrow the bet with one of the biggest influencers on Crypto Twitter, Cobie. While all 3 of the bettors in this scenario decided that Cobie was trustworthy enough to secure tens of millions of dollars on a gamble, there is no doubt that under normal circumstances, securing such sums of money with a person you've never met before on Twitter is questionable at best. That's where Ready Set Bet comes in, aiming to be a platform to secure just such bets or virtually any bet whatsoever.</p>
        <h1 className="text-xl text-slate-200 p-5 border-b-2">Where is Ready Set Bet at currently?</h1>
        <p>Well, this project was only ideated and built within the span of the ETHBogota 2022 conference. There's no doubt that there is still alot of work to be done. First and foremost, the UI needs to be completed. Without a smooth UX, it is unlikely that people would ever use the platform even if it was secure. Next, the contracts need to be examined with more scrutiny. While contracts have been tested to a reasonable degree manually for basic functionality, that is no substitute for an extensive testing suite and a professional audit. Furthermore, there is a small amount of work to still do building the base functionality of the contracts as on Mainnet UMA charges fees that have not been accounted for on Goerli Testnet, however, the work shouldn't be too extensive to accommodate such fees. Once the UI is finished and the contracts have been fleshed out a little more, the platform is more or less ready to launch for its V1. The idea is actually quite simple as UMA takes care of all the heavy lifting by creating a secure platform that assures proper voting and outcome resolution through their game theory mechanics.</p>
        <h1 className="text-xl text-slate-200 p-5 border-b-2">How does Ready Set Bet work?</h1>
        <p>As previously mentioned, this protocol is only possible due to UMA's ingenious settlement system. In basic terms, Ready Set Bet allows users to create betting 1v1 betting contracts with any type of publicy verifiable open word question, such as those mentioned above. Users are able to create both public and private bets, depositing a wager into the bet. Once the bet has been made and the wager has been deposited into the Ready Set Bet contract, either another non-specific or specific bettor can take up the bet, depending on whether or not the bet is private. Once the bet has been initialized with both sides of the wager, either one of the users can request that UMA settle the contract once the conditions of the wager have been triggered. Ready Set Bet is very flexible in that it can support all 115 of the different assets that UMA currently supports as collateral. Bets can also be asymmetrical, meaning that both sides of the bet do not need to wager the same amount. For example, Ready Set Bet can also support a wager such as a 10-to-1 bet that the price of Bitcoin falls below $5k USD within 2022. In this way, Ready Set Bet can in theory provide a service similar to options.</p>
        <h1 className="text-xl text-slate-200 p-5 border-b-2">What does the protocol have in store for the future?</h1>
        <p>Once V1 is finished and ready for production, there is a plan for a V2 which could greatly increase the utility and adoption of Ready Set Bet. Currently, the protocol is designed to store bet information and collateral within the contract itself, allowing users to interact with the platform in the manners described above in a somewhat limited way. For V2, I think it would be possible to mint ERC1155 semi-fungible tokens to manage these positions. As 1155s, active wagers on Ready Set Bet could be minted en masse and traded on platforms such as OpenSea. Like this, the bets become even closer to traditional financial options. The inherently decentralized nature of Ready Set Bet could allow users to not only trade options with greater freedom, but issue them as well. For example, let's say that a user decides to mint 500 10-to-1 wagers, depositing $1000 into each contract, that the price of Bitcoin will go below $5k USD by the end of 2022. In this scenario, the user has a great deal of financial flexibility in what they do with these contracts as they reach closer to expiry. They can gamble with them, hedge their portfolio, or really anything that a traditional option could do. The advantage of this architecture as opposed to other web3 predictions markets or options platforms is that UMA's system allows for virtually any wager at any scale or timeframe. Users are not limited by nearly anything as long as they provide UMA an answerable question. From two friends having a friendly wager to serious financial strategies, from a contract settled tomorrow to a contract settled in 3 years, Ready Set Bet can handle it all. Futhermore, with this ERC1155 design, the platform becomes much more efficient as a single verification request to UMA could theoretically settle an infinite number of contracts as opposed to the current design that requrie 1 request per wager. Big ideas and lots of ifs, but it's worth a shot I think.</p>
      </div>
    </div>
  )
}