import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BetBox from '../components/BetBox';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BetBox
        betHandlerAddress={"0x430E709FECa7C7c304e29F3b9633D9a8f8F03554"}
        betId={0}
      />
    </div>
  )
}