import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Form, useNotification, Button } from "web3uikit";
import { useWeb3Contract } from "react-moralis";
import { useMoralis } from "react-moralis";
import { ethers } from "ethers";
import betHandlerAbi from "../constants/betHandlerAbi";

export default function Home() {
  const { chainId: chainIdHex, isWeb3Enabled } = useMoralis();
  const chainId = parseInt(chainIdHex);
  const contractAddress = "0x430E709FECa7C7c304e29F3b9633D9a8f8F03554"


  const { runContractFunction: setBet, isLoading, isFetching } = useWeb3Contract({
    abi: betHandlerAbi,
    contractAddress: contractAddress,
    functionName: "setBet",
    params: {

    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        className={styles.container}
        onSubmit={console.log("Yay")}
        data={[
          {
            name: "What's your bet?",
            type: "textarea",
            inputWidth: "50%",
            value: "",
            key: "question"
          },
          {
            name: "Token (address) to Bet",
            type: "text",
            value: "",
            key: "bondCurrency"
          },
          {
            name: "Validation Reward",
            type: "number",
            value: "",
            key: "reward"
          },
          {
            name: "Liveness Period",
            type: "number",
            value: "",
            key: "liveness"
          },
          {
            name: "Private Bet?",
            type: "text",
            value: "",
            key: "privateBet"
          },
          {
            name: "Private Bet Recipient",
            type: "text",
            value: "",
            key: "privateBetRecipient"
          },
          {
            name: "Are you affirming the bet?",
            type: "text",
            value: "",
            key: "affirmationBool"
          },
          {
            name: "How much do you want to bet?",
            type: "number",
            value: "",
            key: "betAmount"
          },
          {
            name: "How much should your counterparty bet?",
            type: "number",
            value: "",
            key: "counterBetAmount"
          }
        ]}
        title="Set Your Bet!"
        id="Main Form"
      />
    </div>
  )
}
